version: '3'

services:
  api:
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["./run.sh"]
    ports: 
      - 8000:8000
    networks:
      - dev
    depends_on:
      - db

  db:
    image: mongo:3.2.21-jessie
    networks:
      - dev

networks:
  dev: